apiVersion: v1
kind: Service
metadata:
  name: app-name-service
  labels:
    svc: app-name
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-name
