apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: app-name-ingress
spec:
  rules:
  - host: app-name.jrvs
    http:
      paths:
      - path: /
        backend:
          serviceName: app-name-service
          servicePort: 8080
